apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-queue-scaler
  namespace: awe
spec:
  scaleTargetRef:
    name: worker
  pollingInterval: 10
  cooldownPeriod: 180
  minReplicaCount: 2
  maxReplicaCount: 30
  triggers:
    - type: redis-streams
      metadata:
        address: redis:6379
        stream: tasks.events
        consumerGroup: workers
        pendingEntriesCount: "20"
